version: '3.8'

services:
  db:
  #todo check if this is the latest postgres version
  #todo adjust sensitive data like user, password, and database name
    image: postgis/postgis:17-3.5-alpine # Using a stable, smaller image with alpine for efficiency
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: platformDB
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  # app:
  #   build: .
  #   command: npm run start:prod
  #   depends_on:
  #     - db
  #   environment:
  #     # NODE_ENV: development # todo Example: uncomment and set to 'production' for prod builds

  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_USERNAME: myuser
  #     DB_PASSWORD: mypass
  #     DB_DATABASE: platformDB
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules

volumes:
  db-data:
